spring:
  application:
    name: complaint-service
  profiles:
    active: ${PROFILE_ACTIVE:dev}
    
server:
  port: 8082

eureka:  client:    fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: ${DISCOVERY_SERVER:http://localhost:8761/eureka}

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: ${MONGODB_DEV_URL}

---
spring:
  profiles: prod
  data:
    mongodb:
      uri: ${MONGODB_URL}
  